SET SERVEROUTPUT ON;

DECLARE

    V_SALARIO NUMBER := 1518.00;
    V_SALARIO_ATUALIZADO NUMBER := V_SALARIO + (v_salario * 0.25);

BEGIN

    DBMS_OUTPUT.PUT_LINE('O SALÁRIO MÍNIMO ATUALIZADO É: ' || V_SALARIO_ATUALIZADO);
END;

DECLARE
    V_DOLARES NUMBER := '&DOLARES';
    V_RAZAO NUMBER := 5.50;
BEGIN
    DBMS_OUTPUT.PUT_LINE( V_DOLARES || ' DOLARES CONVERTIDOS PARA REAIS SÃO ' || V_DOLARES * V_RAZAO || ' REAIS.');
END;

DECLARE
    V_PARCELAS NUMBER := 10;
    V_COMPRA NUMBER := '&VALOR';
BEGIN
    DBMS_OUTPUT.PUT_LINE( 'O VALOR DA PARCELA É DE R$' || ((V_COMPRA * 1.03) / 10));
END;

DECLARE
    V_COMPRA NUMBER := '&VALOR';
    V_PARCELADO NUMBER := V_COMPRA * 0.8;
    V_PARCELA_1 NUMBER := 6;
    V_PARCELA_2 NUMBER := 12;
    V_PARCELA_3 NUMBER := 18;
BEGIN
    DBMS_OUTPUT.PUT_LINE( 'O VALOR DA PARCELA PARA 6 MESES É R$' || ((V_PARCELADO * 1.1) / V_PARCELA_1) );
    DBMS_OUTPUT.PUT_LINE( 'O VALOR DA PARCELA PARA 12 MESES É R$' || ((V_PARCELADO * 1.15) / V_PARCELA_2));
    DBMS_OUTPUT.PUT_LINE( 'O VALOR DA PARCELA PARA 18 MESES É R$' || ((V_PARCELADO * 1.2) / V_PARCELA_3));
END;


