SET SERVEROUTPUT ON;

DECLARE
    VALOR NUMBER := &VALOR;
BEGIN

    IF MOD(VALOR,2) = 0 THEN
        DBMS_OUTPUT.PUT_LINE('O NÚMERO QUE VOCÊ INSERIU É PAR');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O NÚMERO QUE VOCÊ INSERIU É ÍMPAR');
    END IF;
END;

--====================================================================--

DECLARE
    V_LETRA CHAR(1) := '&LETRA';
BEGIN

    IF UPPER(V_LETRA) = 'F' THEN
        DBMS_OUTPUT.PUT_LINE('VOCÊ É UMA MULHER');
    ELSIF UPPER(V_LETRA) = 'M' THEN
        DBMS_OUTPUT.PUT_LINE('VOCÊ É UM CARA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INSIRA "M" OU "F"');
    END IF;
END;

--====================================================================--

DECLARE
    V_COMPRA NUMBER := '&COMPRA';
    V_PARCELADO NUMBER := V_COMPRA * 0.2;
    V_PARCELAS NUMBER := '&N_PARCELAS';
BEGIN

    IF V_PARCELAS = 6 THEN
        DBMS_OUTPUT.PUT_LINE('O VALOR INDIVIDUAL DAS PARCELAS SERÁ R$' || (V_PARCELADO * 1.1)/V_PARCELAS);
    ELSIF V_PARCELAS = 12 THEN
        DBMS_OUTPUT.PUT_LINE('O VALOR INDIVIDUAL DAS PARCELAS SERÁ R$' || (V_PARCELADO * 1.15)/V_PARCELAS);
    ELSIF V_PARCELAS = 18 THEN
        DBMS_OUTPUT.PUT_LINE('O VALOR INDIVIDUAL DAS PARCELAS SERÁ R$' || (V_PARCELADO * 1.2)/V_PARCELAS);
    ELSE
        DBMS_OUTPUT.PUT_LINE('INSIRA UM NÚMERO VÁLIDO PARA PARCELAS');
    END IF;
END;




